server:
  port: 8080

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.31.104:3306/security-starter?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: security-starter
    password: security-starter
  redis:
    host: 127.0.0.1
    database: 0
    port: 6379
    password:

# Mybatis-plus配置
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  global-config:
    db-config:
      id-type: AUTO
  configuration:
    # 打印sql
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


# JWT配置
jwt:
  # 密匙Key
  secret: jwzhang
  # HeaderKey
  tokenHeader: Authorization
  # Token前缀
  tokenPrefix: Bearer
  # 过期时间，单位秒 86400s=24h=1天 1800s=30min
  expiration: 1800
  # 刷新token过期时间 单位天
  refreshTime: 7
  # 配置白名单（不需要认证）
  antMatchers:
    - /login/**
    - /register/**
    - /static/**
    # swagger
    - /v3/api-docs/**
    - /swagger-resources/**
    - /swagger-ui/**
    # 图片验证码
    - /captchaImage

# 项目相关配置
starter:
  # 验证码类型 math 数组计算 char 字符验证
  captchaType: math
  # 是否开启swagger
  swagger:
    enable: true

# 防止XSS攻击
xss:
  # 过滤开关
  enabled: true
  # 排除链接（多个用逗号分隔）
  excludes: /system/notice/*
  # 匹配链接
  urlPatterns: /system/*,/monitor/*,/tool/*
